'''
Code to plot the distributions generated by a null model. The simulations are centered on analyzing the expected behavior of the distribution of a maximum among n secondary objects generated.
Taking a whole (100%), how much is it expected that, when we partition this whole through a uniform random process, the largest of the generated fractions takes from the total percentage?
To study the phenomenon, I model the system starting from a generic object: a stick (which, in the context of the research on the leading particle effect, can be interpreted as the total energy of the primary) of length 1.
The idea is simple: through a random process based on a uniform distribution, generate n-1 breaking points within this stick of length 1 (n-1 random numbers between 0 and 1) to produce n fractions of the stick.
From these n fractions, we keep the value of the largest one.
By repeating the process thousands of times, we can plot the distribution of maxima generated from a uniform distribution.
'''

import matplotlib.pyplot as plt
import numpy as np
import random
from math import factorial


def run_simulation(R, N):
    lista_maiores = []

    for _ in range(R):
        lista_cortes = sorted(random.random() for _ in range(N - 1))

        lista_tamanhos = [lista_cortes[0]] + \
                         [lista_cortes[i] - lista_cortes[i - 1] for i in range(1, len(lista_cortes))] + \
                         [1 - lista_cortes[-1]]

        maior = max(lista_tamanhos)
        lista_maiores.append(maior)

    return lista_maiores


def compute_statistics(data, N, x, R):
    def valor_medio(h: float, n: int) -> float:
        return h / n

    H = sum(1 / k for k in range(1, N + 1))
    media_teorica = valor_medio(H, N)

    contagem = sum(1 for v in data if v < x)
    prob_exp = contagem / R

    def Prob_Max(n: int, x: float) -> float:
        ListaSoma = [
            (factorial(n) / (factorial(i) * factorial(n - i))) *
            ((-1) ** (i - 1)) *
            ((1 - i * x) ** (n - 1))
            for i in range(1, n + 1) if (1 - (i * x)) > 0
        ]
        return sum(ListaSoma)

    prob_teorica = 1 - Prob_Max(N, x)

    return media_teorica, prob_exp, prob_teorica


def plot_distribution(data, x):
    counts, bins = np.histogram(data, bins=100, density=True)

    bin_width = bins[1] - bins[0]
    density = counts * bin_width
    bin_centers = (bins[:-1] + bins[1:]) / 2

    media_histograma = np.sum(bin_centers * density)

    plt.bar(bins[:-1], density, width=bin_width, edgecolor='black', align='edge')
    plt.axvline(x, color='r', linestyle='--', label=f'x = {x}')
    plt.axvline(media_histograma, color='g', linestyle='-', label=f'Mean = {media_histograma:.4f}')

    plt.xlabel('Size of the Largest Piece')
    plt.ylabel('Intrinsic Probability')
    plt.title('Distribution of the Largest Pieces')
    plt.legend()
    plt.show()

    return media_histograma


# ===== MAIN =====

if __name__ == "__main__":
    R = int(input("How many times do you want to run the program? "))
    N = int(input("Into how many pieces do you want to divide the stick? "))
    x = float(input("Which parameter value should be used? "))

    data = run_simulation(R, N)

    media_teorica, prob_exp, prob_teorica = compute_statistics(data, N, x, R)

    media_hist = plot_distribution(data, x)

    print(f"The theoretical mean value is: {media_teorica}")
    print(f"Histogram mean value: {media_hist}")
    print(f"Experimental probability <= {x}: {prob_exp}")
    print(f"Theoretical probability of being <= {x}: {prob_teorica}")
